# Generated by Django 5.2.4 on 2025-07-23 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0002_alter_employee_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='place',
        ),
        migrations.DeleteModel(
            name='ParkingPlace',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
