# Generated by Django 5.2.4 on 2025-07-23 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0003_remove_reservation_place_delete_parkingplace_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='History',
        ),
    ]
