# Generated by Django 5.2.4 on 2025-07-23 03:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=5, unique=True)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('vehicule_type', models.CharField(choices=[('car', 'Car'), ('motorcycle', 'Motorcycle')], max_length=10)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration', models.FloatField(blank=True, null=True)),
                ('price', models.FloatField(default=0)),
                ('payment_type', models.CharField(blank=True, choices=[('cash', 'Cash'), ('credit_card', 'Credit Card')], max_length=20, null=True)),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes/')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_app.parkingplace')),
            ],
        ),
    ]
