# Generated by Django 5.2.4 on 2025-07-23 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0002_parkingplace_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.PositiveIntegerField(unique=True)),
                ('vehicule_type', models.CharField(choices=[('car', 'Car'), ('motorcycle', 'Motorcycle')], max_length=10)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration', models.FloatField()),
                ('payment_type', models.CharField(choices=[('cash', 'Cash'), ('credit_card', 'Credit Card')], max_length=20)),
                ('price', models.FloatField()),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes/')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='client_app.parkingplace')),
            ],
        ),
    ]
